[env:esp32s3]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/53.03.11/platform-espressif32.zip
board = esp32-s3-devkitc-1
framework = arduino
monitor_speed = 115200
lib_deps =
    waspinator/AccelStepper @ ^1.64
    asukiaaa/XboxSeriesXControllerESP32_asukiaaa @ ^1.1.1
