<?xml version="1.0"?>
<package format="3">
  <name>perception_module</name>
  <version>0.1.0</version>
  <description>
    Perception module for Alaz autonomous vehicle.
    2D LiDAR LaserScan to Occupancy Grid for obstacle avoidance.
  </description>

  <maintainer email="egekksal@gmail.com">Ege Köksal</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <!-- Runtime deps (launch-time) -->
  <exec_depend>pointcloud_to_laserscan</exec_depend>
  <exec_depend>autoware_probabilistic_occupancy_grid_map</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
