packages:
  rdw_vehicle_launch:
    enabled: true
    launch_file: "vehicle.launch.xml"
  
  ros2_can_bridge:
    enabled: true
    launch_file: "ros2_can_bridge.launch.py"
  
  rdw_sensor_kit_launch:
    enabled: true
    launch_file: "sensing.launch.xml"

  odometry:
    enabled: true
    launch_file: "my_odom.launch.xml"

  alaz_lidar_clustering:
    enabled: true
    launch_file: "lidar_clustering.launch.xml"
  
  localization:
    enabled: true
    launch_file: "localization.launch.py"

  perception_module:
    enabled: true
    launch_file: "perception.launch.xml"

  planning:
    enabled: true
    launch_file: "planning.launch.py"
    
  control:
    enabled: true
    launch_file: "control.launch.py"
    
  mission_control:
    enabled: true
    launch_file: "mission_control.launch.xml"
