packages:
  my_vehicle_launch:
    enabled: true
    launch_file: "vehicle.launch.xml"
    arguments:
      can_interface: "can0"
      launch_can_bridge: "true"
  
  rdw_sensor_kit_launch:
    enabled: true
    launch_file: "sensing.launch.xml"

  odometry:
    enabled: true
    launch_file: "my_odom.launch.xml"

  alaz_lidar_clustering:
    enabled: true
    launch_file: "lidar_clustering.launch.xml"
  
  localization:
    enabled: true
    launch_file: "localization.launch.py"
    arguments:
      lanelet2_map_path: "/workspace/maps/map.osm"

  perception:
    enabled: true
    launch_file: "perception.launch.xml"

  planning:
    enabled: true
    launch_file: "planning.launch.py"
    
  control:
    enabled: true
    launch_file: "control.launch.py"
    
  mission_control:
    enabled: true
    launch_file: "mission_control.launch.xml"
