packages:
  my_vehicle_launch:
    enabled: true
    launch_file: "vehicle.launch.xml"
    arguments:
      launch_can_bridge: "false"
    
  pseudo_vehicle_data:
    enabled: true
    launch_file: "pseudo_vehicle_data.launch.py"

  dummy_camera:
    enabled: true
    launch_file: "dummy_camera.launch.py"
    
  dummy_lidar:
    enabled: true
    launch_file: "dummy_lidar.launch.py"
  
  rdw_sensor_kit_launch:
    enabled: false
    launch_file: "sensing.launch.xml"

  odometry:
    enabled: true
    launch_file: "my_odom.launch.xml"

  alaz_lidar_clustering:
    enabled: true
    launch_file: "lidar_clustering.launch.xml"
  
  localization:
    enabled: true
    launch_file: "localization.launch.py"

  perception:
    enabled: true
    launch_file: "perception.launch.xml"

  planning:
    enabled: false #deneme amaçlı false yaptım(izzet)
    launch_file: "planning.launch.py"
    
  control:
    enabled: false
    launch_file: "control.launch.py"
    
  mission_control:
    enabled: false
    launch_file: "mission_control.launch.xml"
