<?xml version="1.0"?>
<package format="3">
  <name>tier4_perception_launch</name>
  <version>0.1.0</version>
  <description>Multi-camera 2D detection and tracking launch orchestration.</description>
  <maintainer email="zuhalkoksal@example.com">zuhalkoksal</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <exec_depend>launch</exec_depend>
  <exec_depend>launch_xml</exec_depend>
  <exec_depend>autoware_tensorrt_yolox</exec_depend>
  <exec_depend>autoware_bytetrack</exec_depend>
  <exec_depend>autoware_traffic_light_classifier</exec_depend>
  <exec_depend>autoware_detection_autoware_bridge</exec_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
