base_link:
  sensor_kit_base_link:
    x: 0.8   # Arka akstan 80cm önde (Tavana veya ön kaputa yakın)
    y: 0.0   # Aracın tam ortasında
    z: 1.55  # Yerden 1.55m yüksekte (Tavan hizası varsayıldı)
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
