sensor_kit_base_link:
  camera_center_link:
    x: 0.98
    y: 0.0
    z: 0.39
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  camera_left_link:
    x: 0.98
    y: 0.0
    z: 0.39
    roll: 0.0
    pitch: 0.0
    yaw: 0.52

  camera_right_link:
    x: 0.98
    y: 0.0
    z: 0.39
    roll: 0.0
    pitch: 0.0
    yaw: -0.52

  lidar_link:
    x: 1.36
    y: 0.0
    z: 0.17
    roll: 0.0
    pitch: 0.0
    yaw: 0.0

  gnss_link:
    x: 0.0
    y: 0.0
    z: 0.0
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
