<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>rdw_sensor_kit_description</name>
  <version>0.1.0</version>
  <description>The rdw_sensor_kit_description package for 3 Cameras and 1 2D LiDAR</description>
  <maintainer email="kekecmehmet71@gmail.com">Mehmet Kekeç</maintainer>
  <license>Apache License 2.0</license>

  <buildtool_depend>ament_cmake_auto</buildtool_depend>

  <!-- Kamera modelleri için gerekli -->
  <exec_depend>camera_description</exec_depend>
  
  <!-- xacro dosyalarını işlemek için gerekli -->
  <exec_depend>xacro</exec_depend>

  <!-- Eğer 2D Lidarınız için özel bir ROS paketi varsa (örn: sick_scan, rplidar_ros) buraya ekleyin.
       Yoksa standart geometrik şekillerle temsil edeceğimiz için ek bağımlılığa gerek yok. -->

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
